<?php
return [
'header' => '4-STAR HOTEL TWO STEPS AWAY FROM THE CHAMPS ELYSÉE AND THE ARC DE TRIOMPHE',
'price' => 'starting from',
'single' => 'With a single bed and a shower room, this room is ideal for accommodating a business person in the heart of Paris. Overlooking the interior courtyard, it offers a peaceful and serene setting conducive to rest. Cozy and delicate, our Single room will delight you with its softness and will become your haven of peace for a few nights.',
'classique' => 'Enjoying an exhibition on the interior of the hotel or on the Chateaubriand street parallel to the Champs-Elysées, this stylish room offers unbeatable comfort and calm. With a double bed and a marble bathroom, it embodies Parisian charm and elegance in a warm decor, meticulously cared for for your comfort.',
'superieure' => 'Synonymous with refinement, most of our Superior rooms enjoy a view of Avenue de Friedland, a majestic tree-lined artery in the axis of the Arc de Triomphe. Elegant and warm, the Superior room invites you to experience an exceptional stay in the heart of Paris.',
'deluxe' => 'The Deluxe room reflects the refinement of the Superior room and offers you the softness and discreet luxury for 3 people. In this spacious space, you can enjoy a double bed and an extra bed that can accommodate up to three people. Luxurious, warm and refined, the Deluxe room will charm you as soon as you arrive in Paris to make you enjoy an unforgettable moment with us.',
'executive' => 'Do you like extreme refinement? Proud of its exceptional location, the Executive room will not disappoint. During your stay, it will be the place where you will like to rest and enjoy an exceptional view of the Arc de Triomphe, depending on the floors, after having benefited from the thousand attractions of Parisian life. The Executive room has a large bed, a nice bathroom and a space for tea. This elegant room will charm you with its Parisian authenticity mixed with a majestic setting.',
'familiale' => 'The Family room, a reflection of space and well-being, offers the softness of subtle and discreet luxury. In this space with remarkable volume, you can enjoy a double bed and a sofa bed for up to four people. Luxurious, warm and refined, the family room will charm you as soon as you arrive in Paris to offer you the best of stays.',
];