<?php
return [
'header' => 'HÔTEL 4 ÉTOILES À DEUX PAS DES CHAMPS ELYSÉES ET DE L’ARC DE TRIOMPHE',
'price' => 'À partir de',
'single' => 'Dotée d’un lit simple et d’une salle de douche, cette chambre est idéale pour accueillir une personne en voyage d’affaire en plein cœur de Paris. Donnant sur la cour intérieure, elle offre un cadre paisible et serein propice au repos. Cosy et délicate, notre chambre Simple vous ravira par sa douceur et deviendra votre havre de paix le temps de quelques nuits..',
'classique' => 'Jouissant d’une exposition sur l\'intérieur de l\'hôtel ou sur la rue Chateaubriand parallèle aux Champs-Elysées, cette chambre coquette offre un confort et un calme inégalables. Dotée d’un lit double et d’une salle de bain en marbre, elle incarne le charme et l’élégance à la parisienne dans un décor chaleureux, soigné avec minutie pour votre plus grand confort.',
'superieure' => 'Synonyme de raffinement, la plupart de nos chambres Supérieures bénéficient d’une vue sur l\'avenue de Friedland, artère arborée majestueuse dans l\'axe de l\'Arc de Triomphe. Elégante et chaleureuse, la chambre Supérieure vous invite à l’expérience d’un séjour exceptionnel au cœur de Paris..',
'deluxe' => 'La chambre Deluxe, reflète le raffinement de la chambre Supérieure et vous offre la douceur et le luxe discret pour 3 personnes. Dans cet espace au beau volume, vous pourrez profiter d’un lit double ainsi que d’un lit d’appoint permettant d’accueillir jusqu’à trois personnes. Luxueuse, chaleureuse et raffinée, la chambre Deluxe vous charmera dès votre arrivée à Paris pour vous faire profiter d’un moment inoubliable parmi nous.',
'executive' => 'Vous aimez l\'extrême raffinement ? Fière de sa situation exceptionnelle, la chambre Executive ne vous décevra pas. Elle sera, le temps de votre séjour, l\'endroit où vous aimerez vous reposer et jouir d\'une vue exceptionnelle sur l’Arc de Triomphe, en fonction des étages, après avoir profité des mille attraits de la vie parisienne. La chambre Executive bénéficie d’un grand lit, d’une jolie salle de bain ainsi que d’un espace pour prendre le thé. Cette chambre élégante saura vous charmer par son authenticité parisienne mêlée à un cadre majestueux.',
'familiale' => 'La chambre Familiale, reflet d\'espace et de bien-être, offre la douceur d\'un luxe subtil et discret. Dans cet espace au volume remarquable, vous pourrez profiter d’un lit double ainsi que d’un canapé-lit permettant d’accueillir jusqu’à quatre personnes. Luxueuse, chaleureuse et raffinée, la chambre familiale vous charmera dès votre arrivée à Paris pour vous offrir le meilleur des séjours.',
];